name: ∞
favicon: null
layout_spectrum: 0.05582036776468158
typography_spectrum: 0.07929903292097151
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#151412'
    - '#d6976e'
    - '#00b1de'
    - '#0059bf'
  brandStrength: 0.6875
  lightness: 0.375
  saturation: 0.1875
  rhythmicContrast: 0.5042801215313375
purpose: []
